 [module/yay-updates]
 type = custom/script
 exec = ~/.config/polybar/scripts/updates-arch-yay.sh
 interval = 3600000
 click-left = i3-msg exec ~/.config/polybar/scripts/updates-arch-yay.sh
; click-right = i3-msg exec ~/.config/polybar/scripts/prompt-updates.sh
